### PR TITLE
Feature/applied sessions

### PR DESCRIPTION
**Pull request by Jing-Kai**
assign to @irisschen

# what
- change the goal to session-based recommendations
- pick out sessions with more than n + k events, where n = 20 and k = 5
- split the metering into 4 parquet files, namely label_[train|test]_[source|target]
- implement 2 tests: one for handling song_id, and the other for handling session id cardinality.

### CODE REVIEW

**Comment by irisschen** [comment]
I encountered some errors while running `dbt test`.
```
02:08:01  3 of 6 FAIL 53174 dbt_utils_cardinality_equality_split_test_source_sid__sid__ref_filter_test_sessions_  [FAIL 53174 in 225.69s]
02:11:01  6 of 6 FAIL 165384 dbt_utils_cardinality_equality_split_train_target_sid__sid__ref_filter_train_sessions_  [FAIL 165384 in 291.54s]
02:11:31  5 of 6 FAIL 165384 dbt_utils_cardinality_equality_split_train_source_sid__sid__ref_filter_train_sessions_  [FAIL 165384 in 420.23s]
02:11:32  4 of 6 FAIL 53174 dbt_utils_cardinality_equality_split_test_target_sid__sid__ref_filter_test_sessions_  [FAIL 53174 in 436.49s]
02:11:33
02:11:33  Finished running 6 tests in 0 hours 7 minutes and 18.73 seconds (438.73s).
02:11:33
02:11:33  Completed with 4 errors and 0 warnings:
02:11:33
02:11:33  Failure in test dbt_utils_cardinality_equality_split_test_source_sid__sid__ref_filter_test_sessions_ (models/stage/_stage_models.yml)
02:11:33    Got 53174 results, configured to fail if != 0
02:11:33
02:11:33    compiled Code at target/compiled/dg23_explorer2/models/stage/_stage_models.yml/dbt_utils_cardinality_equality_0943adad0eb0036f541d64eb230246e8.sql
02:11:33
02:11:33  Failure in test dbt_utils_cardinality_equality_split_train_target_sid__sid__ref_filter_train_sessions_ (models/stage/_stage_models.yml)
02:11:33    Got 165384 results, configured to fail if != 0
02:11:33
02:11:33    compiled Code at target/compiled/dg23_explorer2/models/stage/_stage_models.yml/dbt_utils_cardinality_equality_8f2e00990d2608be14ee460b410a7a68.sql
02:11:33
02:11:33  Failure in test dbt_utils_cardinality_equality_split_train_source_sid__sid__ref_filter_train_sessions_ (models/stage/_stage_models.yml)
02:11:33    Got 165384 results, configured to fail if != 0
02:11:33
02:11:33    compiled Code at target/compiled/dg23_explorer2/models/stage/_stage_models.yml/dbt_utils_cardinality_equality_086eb1856dbe28bab824b5b1df7f8b83.sql
02:11:33
02:11:33  Failure in test dbt_utils_cardinality_equality_split_test_target_sid__sid__ref_filter_test_sessions_ (models/stage/_stage_models.yml)
02:11:33    Got 53174 results, configured to fail if != 0
02:11:33
02:11:33    compiled Code at target/compiled/dg23_explorer2/models/stage/_stage_models.yml/dbt_utils_cardinality_equality_bfc00f20cfbe5fbd933b43e2fa8c29ca.sql
```

**Comment by Jing-Kai** [comment]
Thanks for the feedback.

I use in-memory duckdb and output external to s3 bucket. so I didn't run `dbt test` previously. Could you share how you manage the intermedium helping me to reproduce the case.

**Comment by Jing-Kai** [comment]
Figured it out.

The cardinality equality test is not the desired one. Will change that.

**Comment by Jing-Kai** [comment]
The equality is the expected one checking if two columns are set equality. See [URL](https://github.com/dbt-labs/dbt-utils#equality-source) 

The cardinality equality require both group key and group size are identical. Which is not desire in our case. See [URL](https://github.com/dbt-labs/dbt-utils#cardinality_equality-source)

image

**Comment by Jing-Kai** [comment]
@irisschen Let me merge it.

**Pull request merged**
